/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SortRouteImport } from './routes/sort'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as JoinAsProRouteImport } from './routes/join-as-pro'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BizRouteImport } from './routes/biz'
import { Route as BiometricEnrollRouteImport } from './routes/biometric-enroll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as SafetyIndexRouteImport } from './routes/safety.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as SigninGoogleRouteImport } from './routes/signin.google'
import { Route as SigninAppleRouteImport } from './routes/signin.apple'
import { Route as SeeAllCategoryRouteImport } from './routes/see-all.$category'
import { Route as SafetyReportRouteImport } from './routes/safety.report'
import { Route as SafetyEmergencyContactsRouteImport } from './routes/safety.emergency-contacts'
import { Route as SafetyDiscreetCallRouteImport } from './routes/safety.discreet-call'
import { Route as ProfileThemeRouteImport } from './routes/profile.theme'
import { Route as ProfileTermsRouteImport } from './routes/profile.terms'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileReferRouteImport } from './routes/profile.refer'
import { Route as ProfileRatingRouteImport } from './routes/profile.rating'
import { Route as ProfilePromotionsRouteImport } from './routes/profile.promotions'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfilePaymentMethodsRouteImport } from './routes/profile.payment-methods'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileLegalRouteImport } from './routes/profile.legal'
import { Route as ProfileLanguageRouteImport } from './routes/profile.language'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileHairProfileRouteImport } from './routes/profile.hair-profile'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileCreditsRouteImport } from './routes/profile.credits'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as ProProIdRouteImport } from './routes/pro.$proId'
import { Route as PoliciesCancellationRouteImport } from './routes/policies.cancellation'
import { Route as FavoritesCollectionIdRouteImport } from './routes/favorites.$collectionId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BizSigninRouteImport } from './routes/biz.signin'
import { Route as ProProIdIndexRouteImport } from './routes/pro.$proId.index'
import { Route as ProProIdReviewsRouteImport } from './routes/pro.$proId.reviews'
import { Route as ProProIdPortfolioRouteImport } from './routes/pro.$proId.portfolio'
import { Route as BookingSearchingBookingIdRouteImport } from './routes/booking.searching.$bookingId'
import { Route as BookingRescheduleBookingIdRouteImport } from './routes/booking.reschedule.$bookingId'
import { Route as BookingReceiptBookingIdRouteImport } from './routes/booking.receipt.$bookingId'
import { Route as BookingRateBookingIdRouteImport } from './routes/booking.rate.$bookingId'
import { Route as BookingPendingBookingIdRouteImport } from './routes/booking.pending.$bookingId'
import { Route as BookingMessageBookingIdRouteImport } from './routes/booking.message.$bookingId'
import { Route as BookingConfirmProIdRouteImport } from './routes/booking.confirm.$proId'
import { Route as BookingCancelledBookingIdRouteImport } from './routes/booking.cancelled.$bookingId'
import { Route as BookingCancelBookingIdRouteImport } from './routes/booking.cancel.$bookingId'
import { Route as BookingCallBookingIdRouteImport } from './routes/booking.call.$bookingId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SortRoute = SortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsProRoute = JoinAsProRouteImport.update({
  id: '/join-as-pro',
  path: '/join-as-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BizRoute = BizRouteImport.update({
  id: '/biz',
  path: '/biz',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricEnrollRoute = BiometricEnrollRouteImport.update({
  id: '/biometric-enroll',
  path: '/biometric-enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SigninRoute,
} as any)
const SafetyIndexRoute = SafetyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SafetyRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FavoritesRoute,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const SigninGoogleRoute = SigninGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => SigninRoute,
} as any)
const SigninAppleRoute = SigninAppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => SigninRoute,
} as any)
const SeeAllCategoryRoute = SeeAllCategoryRouteImport.update({
  id: '/see-all/$category',
  path: '/see-all/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyReportRoute = SafetyReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SafetyRoute,
} as any)
const SafetyEmergencyContactsRoute = SafetyEmergencyContactsRouteImport.update({
  id: '/emergency-contacts',
  path: '/emergency-contacts',
  getParentRoute: () => SafetyRoute,
} as any)
const SafetyDiscreetCallRoute = SafetyDiscreetCallRouteImport.update({
  id: '/discreet-call',
  path: '/discreet-call',
  getParentRoute: () => SafetyRoute,
} as any)
const ProfileThemeRoute = ProfileThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileTermsRoute = ProfileTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileReferRoute = ProfileReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRatingRoute = ProfileRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePromotionsRoute = ProfilePromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentMethodsRoute = ProfilePaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLegalRoute = ProfileLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLanguageRoute = ProfileLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHairProfileRoute = ProfileHairProfileRouteImport.update({
  id: '/hair-profile',
  path: '/hair-profile',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileCreditsRoute = ProfileCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ProfileRoute,
} as any)
const ProProIdRoute = ProProIdRouteImport.update({
  id: '/pro/$proId',
  path: '/pro/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesCancellationRoute = PoliciesCancellationRouteImport.update({
  id: '/policies/cancellation',
  path: '/policies/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesCollectionIdRoute = FavoritesCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => FavoritesRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BookingsRoute,
} as any)
const BizSigninRoute = BizSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => BizRoute,
} as any)
const ProProIdIndexRoute = ProProIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProProIdRoute,
} as any)
const ProProIdReviewsRoute = ProProIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProProIdRoute,
} as any)
const ProProIdPortfolioRoute = ProProIdPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProProIdRoute,
} as any)
const BookingSearchingBookingIdRoute =
  BookingSearchingBookingIdRouteImport.update({
    id: '/booking/searching/$bookingId',
    path: '/booking/searching/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingRescheduleBookingIdRoute =
  BookingRescheduleBookingIdRouteImport.update({
    id: '/booking/reschedule/$bookingId',
    path: '/booking/reschedule/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingReceiptBookingIdRoute = BookingReceiptBookingIdRouteImport.update({
  id: '/booking/receipt/$bookingId',
  path: '/booking/receipt/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRateBookingIdRoute = BookingRateBookingIdRouteImport.update({
  id: '/booking/rate/$bookingId',
  path: '/booking/rate/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPendingBookingIdRoute = BookingPendingBookingIdRouteImport.update({
  id: '/booking/pending/$bookingId',
  path: '/booking/pending/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingMessageBookingIdRoute = BookingMessageBookingIdRouteImport.update({
  id: '/booking/message/$bookingId',
  path: '/booking/message/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmProIdRoute = BookingConfirmProIdRouteImport.update({
  id: '/booking/confirm/$proId',
  path: '/booking/confirm/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCancelledBookingIdRoute =
  BookingCancelledBookingIdRouteImport.update({
    id: '/booking/cancelled/$bookingId',
    path: '/booking/cancelled/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingCancelBookingIdRoute = BookingCancelBookingIdRouteImport.update({
  id: '/booking/cancel/$bookingId',
  path: '/booking/cancel/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCallBookingIdRoute = BookingCallBookingIdRouteImport.update({
  id: '/booking/call/$bookingId',
  path: '/booking/call/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/biz': typeof BizRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/join-as-pro': typeof JoinAsProRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/safety': typeof SafetyRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRoute
  '/sort': typeof SortRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/biz/signin': typeof BizSigninRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/pro/$proId': typeof ProProIdRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/credits': typeof ProfileCreditsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/hair-profile': typeof ProfileHairProfileRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/legal': typeof ProfileLegalRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment-methods': typeof ProfilePaymentMethodsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/promotions': typeof ProfilePromotionsRoute
  '/profile/rating': typeof ProfileRatingRoute
  '/profile/refer': typeof ProfileReferRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/safety/discreet-call': typeof SafetyDiscreetCallRoute
  '/safety/emergency-contacts': typeof SafetyEmergencyContactsRoute
  '/safety/report': typeof SafetyReportRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/signin/apple': typeof SigninAppleRoute
  '/signin/google': typeof SigninGoogleRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/booking/call/$bookingId': typeof BookingCallBookingIdRoute
  '/booking/cancel/$bookingId': typeof BookingCancelBookingIdRoute
  '/booking/cancelled/$bookingId': typeof BookingCancelledBookingIdRoute
  '/booking/confirm/$proId': typeof BookingConfirmProIdRoute
  '/booking/message/$bookingId': typeof BookingMessageBookingIdRoute
  '/booking/pending/$bookingId': typeof BookingPendingBookingIdRoute
  '/booking/rate/$bookingId': typeof BookingRateBookingIdRoute
  '/booking/receipt/$bookingId': typeof BookingReceiptBookingIdRoute
  '/booking/reschedule/$bookingId': typeof BookingRescheduleBookingIdRoute
  '/booking/searching/$bookingId': typeof BookingSearchingBookingIdRoute
  '/pro/$proId/portfolio': typeof ProProIdPortfolioRoute
  '/pro/$proId/reviews': typeof ProProIdReviewsRoute
  '/pro/$proId/': typeof ProProIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/biz': typeof BizRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/join-as-pro': typeof JoinAsProRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sort': typeof SortRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/biz/signin': typeof BizSigninRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/credits': typeof ProfileCreditsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/hair-profile': typeof ProfileHairProfileRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/legal': typeof ProfileLegalRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment-methods': typeof ProfilePaymentMethodsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/promotions': typeof ProfilePromotionsRoute
  '/profile/rating': typeof ProfileRatingRoute
  '/profile/refer': typeof ProfileReferRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/safety/discreet-call': typeof SafetyDiscreetCallRoute
  '/safety/emergency-contacts': typeof SafetyEmergencyContactsRoute
  '/safety/report': typeof SafetyReportRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/signin/apple': typeof SigninAppleRoute
  '/signin/google': typeof SigninGoogleRoute
  '/bookings': typeof BookingsIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/safety': typeof SafetyIndexRoute
  '/signin': typeof SigninIndexRoute
  '/booking/call/$bookingId': typeof BookingCallBookingIdRoute
  '/booking/cancel/$bookingId': typeof BookingCancelBookingIdRoute
  '/booking/cancelled/$bookingId': typeof BookingCancelledBookingIdRoute
  '/booking/confirm/$proId': typeof BookingConfirmProIdRoute
  '/booking/message/$bookingId': typeof BookingMessageBookingIdRoute
  '/booking/pending/$bookingId': typeof BookingPendingBookingIdRoute
  '/booking/rate/$bookingId': typeof BookingRateBookingIdRoute
  '/booking/receipt/$bookingId': typeof BookingReceiptBookingIdRoute
  '/booking/reschedule/$bookingId': typeof BookingRescheduleBookingIdRoute
  '/booking/searching/$bookingId': typeof BookingSearchingBookingIdRoute
  '/pro/$proId/portfolio': typeof ProProIdPortfolioRoute
  '/pro/$proId/reviews': typeof ProProIdReviewsRoute
  '/pro/$proId': typeof ProProIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/biz': typeof BizRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/join-as-pro': typeof JoinAsProRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/safety': typeof SafetyRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRoute
  '/sort': typeof SortRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/biz/signin': typeof BizSigninRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/pro/$proId': typeof ProProIdRouteWithChildren
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/credits': typeof ProfileCreditsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/hair-profile': typeof ProfileHairProfileRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/legal': typeof ProfileLegalRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment-methods': typeof ProfilePaymentMethodsRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/promotions': typeof ProfilePromotionsRoute
  '/profile/rating': typeof ProfileRatingRoute
  '/profile/refer': typeof ProfileReferRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/safety/discreet-call': typeof SafetyDiscreetCallRoute
  '/safety/emergency-contacts': typeof SafetyEmergencyContactsRoute
  '/safety/report': typeof SafetyReportRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/signin/apple': typeof SigninAppleRoute
  '/signin/google': typeof SigninGoogleRoute
  '/bookings/': typeof BookingsIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/safety/': typeof SafetyIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/booking/call/$bookingId': typeof BookingCallBookingIdRoute
  '/booking/cancel/$bookingId': typeof BookingCancelBookingIdRoute
  '/booking/cancelled/$bookingId': typeof BookingCancelledBookingIdRoute
  '/booking/confirm/$proId': typeof BookingConfirmProIdRoute
  '/booking/message/$bookingId': typeof BookingMessageBookingIdRoute
  '/booking/pending/$bookingId': typeof BookingPendingBookingIdRoute
  '/booking/rate/$bookingId': typeof BookingRateBookingIdRoute
  '/booking/receipt/$bookingId': typeof BookingReceiptBookingIdRoute
  '/booking/reschedule/$bookingId': typeof BookingRescheduleBookingIdRoute
  '/booking/searching/$bookingId': typeof BookingSearchingBookingIdRoute
  '/pro/$proId/portfolio': typeof ProProIdPortfolioRoute
  '/pro/$proId/reviews': typeof ProProIdReviewsRoute
  '/pro/$proId/': typeof ProProIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometric-enroll'
    | '/biz'
    | '/bookings'
    | '/discover'
    | '/favorites'
    | '/join-as-pro'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/search'
    | '/signin'
    | '/signup'
    | '/sort'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/biz/signin'
    | '/bookings/$bookingId'
    | '/favorites/$collectionId'
    | '/policies/cancellation'
    | '/pro/$proId'
    | '/profile/addresses'
    | '/profile/credits'
    | '/profile/edit'
    | '/profile/hair-profile'
    | '/profile/help'
    | '/profile/language'
    | '/profile/legal'
    | '/profile/notifications'
    | '/profile/payment-methods'
    | '/profile/privacy'
    | '/profile/promotions'
    | '/profile/rating'
    | '/profile/refer'
    | '/profile/settings'
    | '/profile/terms'
    | '/profile/theme'
    | '/safety/discreet-call'
    | '/safety/emergency-contacts'
    | '/safety/report'
    | '/see-all/$category'
    | '/signin/apple'
    | '/signin/google'
    | '/bookings/'
    | '/favorites/'
    | '/profile/'
    | '/safety/'
    | '/signin/'
    | '/booking/call/$bookingId'
    | '/booking/cancel/$bookingId'
    | '/booking/cancelled/$bookingId'
    | '/booking/confirm/$proId'
    | '/booking/message/$bookingId'
    | '/booking/pending/$bookingId'
    | '/booking/rate/$bookingId'
    | '/booking/receipt/$bookingId'
    | '/booking/reschedule/$bookingId'
    | '/booking/searching/$bookingId'
    | '/pro/$proId/portfolio'
    | '/pro/$proId/reviews'
    | '/pro/$proId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometric-enroll'
    | '/biz'
    | '/discover'
    | '/join-as-pro'
    | '/map'
    | '/notifications'
    | '/search'
    | '/signup'
    | '/sort'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/biz/signin'
    | '/bookings/$bookingId'
    | '/favorites/$collectionId'
    | '/policies/cancellation'
    | '/profile/addresses'
    | '/profile/credits'
    | '/profile/edit'
    | '/profile/hair-profile'
    | '/profile/help'
    | '/profile/language'
    | '/profile/legal'
    | '/profile/notifications'
    | '/profile/payment-methods'
    | '/profile/privacy'
    | '/profile/promotions'
    | '/profile/rating'
    | '/profile/refer'
    | '/profile/settings'
    | '/profile/terms'
    | '/profile/theme'
    | '/safety/discreet-call'
    | '/safety/emergency-contacts'
    | '/safety/report'
    | '/see-all/$category'
    | '/signin/apple'
    | '/signin/google'
    | '/bookings'
    | '/favorites'
    | '/profile'
    | '/safety'
    | '/signin'
    | '/booking/call/$bookingId'
    | '/booking/cancel/$bookingId'
    | '/booking/cancelled/$bookingId'
    | '/booking/confirm/$proId'
    | '/booking/message/$bookingId'
    | '/booking/pending/$bookingId'
    | '/booking/rate/$bookingId'
    | '/booking/receipt/$bookingId'
    | '/booking/reschedule/$bookingId'
    | '/booking/searching/$bookingId'
    | '/pro/$proId/portfolio'
    | '/pro/$proId/reviews'
    | '/pro/$proId'
  id:
    | '__root__'
    | '/'
    | '/biometric-enroll'
    | '/biz'
    | '/bookings'
    | '/discover'
    | '/favorites'
    | '/join-as-pro'
    | '/map'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/search'
    | '/signin'
    | '/signup'
    | '/sort'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/biz/signin'
    | '/bookings/$bookingId'
    | '/favorites/$collectionId'
    | '/policies/cancellation'
    | '/pro/$proId'
    | '/profile/addresses'
    | '/profile/credits'
    | '/profile/edit'
    | '/profile/hair-profile'
    | '/profile/help'
    | '/profile/language'
    | '/profile/legal'
    | '/profile/notifications'
    | '/profile/payment-methods'
    | '/profile/privacy'
    | '/profile/promotions'
    | '/profile/rating'
    | '/profile/refer'
    | '/profile/settings'
    | '/profile/terms'
    | '/profile/theme'
    | '/safety/discreet-call'
    | '/safety/emergency-contacts'
    | '/safety/report'
    | '/see-all/$category'
    | '/signin/apple'
    | '/signin/google'
    | '/bookings/'
    | '/favorites/'
    | '/profile/'
    | '/safety/'
    | '/signin/'
    | '/booking/call/$bookingId'
    | '/booking/cancel/$bookingId'
    | '/booking/cancelled/$bookingId'
    | '/booking/confirm/$proId'
    | '/booking/message/$bookingId'
    | '/booking/pending/$bookingId'
    | '/booking/rate/$bookingId'
    | '/booking/receipt/$bookingId'
    | '/booking/reschedule/$bookingId'
    | '/booking/searching/$bookingId'
    | '/pro/$proId/portfolio'
    | '/pro/$proId/reviews'
    | '/pro/$proId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiometricEnrollRoute: typeof BiometricEnrollRoute
  BizRoute: typeof BizRouteWithChildren
  BookingsRoute: typeof BookingsRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRouteWithChildren
  JoinAsProRoute: typeof JoinAsProRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SafetyRoute: typeof SafetyRouteWithChildren
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRouteWithChildren
  SignupRoute: typeof SignupRoute
  SortRoute: typeof SortRoute
  SplashRoute: typeof SplashRoute
  UnlockRoute: typeof UnlockRoute
  WelcomeRoute: typeof WelcomeRoute
  PoliciesCancellationRoute: typeof PoliciesCancellationRoute
  ProProIdRoute: typeof ProProIdRouteWithChildren
  SeeAllCategoryRoute: typeof SeeAllCategoryRoute
  BookingCallBookingIdRoute: typeof BookingCallBookingIdRoute
  BookingCancelBookingIdRoute: typeof BookingCancelBookingIdRoute
  BookingCancelledBookingIdRoute: typeof BookingCancelledBookingIdRoute
  BookingConfirmProIdRoute: typeof BookingConfirmProIdRoute
  BookingMessageBookingIdRoute: typeof BookingMessageBookingIdRoute
  BookingPendingBookingIdRoute: typeof BookingPendingBookingIdRoute
  BookingRateBookingIdRoute: typeof BookingRateBookingIdRoute
  BookingReceiptBookingIdRoute: typeof BookingReceiptBookingIdRoute
  BookingRescheduleBookingIdRoute: typeof BookingRescheduleBookingIdRoute
  BookingSearchingBookingIdRoute: typeof BookingSearchingBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sort': {
      id: '/sort'
      path: '/sort'
      fullPath: '/sort'
      preLoaderRoute: typeof SortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-pro': {
      id: '/join-as-pro'
      path: '/join-as-pro'
      fullPath: '/join-as-pro'
      preLoaderRoute: typeof JoinAsProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz': {
      id: '/biz'
      path: '/biz'
      fullPath: '/biz'
      preLoaderRoute: typeof BizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric-enroll': {
      id: '/biometric-enroll'
      path: '/biometric-enroll'
      fullPath: '/biometric-enroll'
      preLoaderRoute: typeof BiometricEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof SigninRoute
    }
    '/safety/': {
      id: '/safety/'
      path: '/'
      fullPath: '/safety/'
      preLoaderRoute: typeof SafetyIndexRouteImport
      parentRoute: typeof SafetyRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/signin/google': {
      id: '/signin/google'
      path: '/google'
      fullPath: '/signin/google'
      preLoaderRoute: typeof SigninGoogleRouteImport
      parentRoute: typeof SigninRoute
    }
    '/signin/apple': {
      id: '/signin/apple'
      path: '/apple'
      fullPath: '/signin/apple'
      preLoaderRoute: typeof SigninAppleRouteImport
      parentRoute: typeof SigninRoute
    }
    '/see-all/$category': {
      id: '/see-all/$category'
      path: '/see-all/$category'
      fullPath: '/see-all/$category'
      preLoaderRoute: typeof SeeAllCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/report': {
      id: '/safety/report'
      path: '/report'
      fullPath: '/safety/report'
      preLoaderRoute: typeof SafetyReportRouteImport
      parentRoute: typeof SafetyRoute
    }
    '/safety/emergency-contacts': {
      id: '/safety/emergency-contacts'
      path: '/emergency-contacts'
      fullPath: '/safety/emergency-contacts'
      preLoaderRoute: typeof SafetyEmergencyContactsRouteImport
      parentRoute: typeof SafetyRoute
    }
    '/safety/discreet-call': {
      id: '/safety/discreet-call'
      path: '/discreet-call'
      fullPath: '/safety/discreet-call'
      preLoaderRoute: typeof SafetyDiscreetCallRouteImport
      parentRoute: typeof SafetyRoute
    }
    '/profile/theme': {
      id: '/profile/theme'
      path: '/theme'
      fullPath: '/profile/theme'
      preLoaderRoute: typeof ProfileThemeRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/terms': {
      id: '/profile/terms'
      path: '/terms'
      fullPath: '/profile/terms'
      preLoaderRoute: typeof ProfileTermsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/refer': {
      id: '/profile/refer'
      path: '/refer'
      fullPath: '/profile/refer'
      preLoaderRoute: typeof ProfileReferRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/rating': {
      id: '/profile/rating'
      path: '/rating'
      fullPath: '/profile/rating'
      preLoaderRoute: typeof ProfileRatingRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/promotions': {
      id: '/profile/promotions'
      path: '/promotions'
      fullPath: '/profile/promotions'
      preLoaderRoute: typeof ProfilePromotionsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payment-methods': {
      id: '/profile/payment-methods'
      path: '/payment-methods'
      fullPath: '/profile/payment-methods'
      preLoaderRoute: typeof ProfilePaymentMethodsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/legal': {
      id: '/profile/legal'
      path: '/legal'
      fullPath: '/profile/legal'
      preLoaderRoute: typeof ProfileLegalRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/language': {
      id: '/profile/language'
      path: '/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof ProfileLanguageRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/hair-profile': {
      id: '/profile/hair-profile'
      path: '/hair-profile'
      fullPath: '/profile/hair-profile'
      preLoaderRoute: typeof ProfileHairProfileRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/credits': {
      id: '/profile/credits'
      path: '/credits'
      fullPath: '/profile/credits'
      preLoaderRoute: typeof ProfileCreditsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/pro/$proId': {
      id: '/pro/$proId'
      path: '/pro/$proId'
      fullPath: '/pro/$proId'
      preLoaderRoute: typeof ProProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/cancellation': {
      id: '/policies/cancellation'
      path: '/policies/cancellation'
      fullPath: '/policies/cancellation'
      preLoaderRoute: typeof PoliciesCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/$collectionId': {
      id: '/favorites/$collectionId'
      path: '/$collectionId'
      fullPath: '/favorites/$collectionId'
      preLoaderRoute: typeof FavoritesCollectionIdRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/biz/signin': {
      id: '/biz/signin'
      path: '/signin'
      fullPath: '/biz/signin'
      preLoaderRoute: typeof BizSigninRouteImport
      parentRoute: typeof BizRoute
    }
    '/pro/$proId/': {
      id: '/pro/$proId/'
      path: '/'
      fullPath: '/pro/$proId/'
      preLoaderRoute: typeof ProProIdIndexRouteImport
      parentRoute: typeof ProProIdRoute
    }
    '/pro/$proId/reviews': {
      id: '/pro/$proId/reviews'
      path: '/reviews'
      fullPath: '/pro/$proId/reviews'
      preLoaderRoute: typeof ProProIdReviewsRouteImport
      parentRoute: typeof ProProIdRoute
    }
    '/pro/$proId/portfolio': {
      id: '/pro/$proId/portfolio'
      path: '/portfolio'
      fullPath: '/pro/$proId/portfolio'
      preLoaderRoute: typeof ProProIdPortfolioRouteImport
      parentRoute: typeof ProProIdRoute
    }
    '/booking/searching/$bookingId': {
      id: '/booking/searching/$bookingId'
      path: '/booking/searching/$bookingId'
      fullPath: '/booking/searching/$bookingId'
      preLoaderRoute: typeof BookingSearchingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/reschedule/$bookingId': {
      id: '/booking/reschedule/$bookingId'
      path: '/booking/reschedule/$bookingId'
      fullPath: '/booking/reschedule/$bookingId'
      preLoaderRoute: typeof BookingRescheduleBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/receipt/$bookingId': {
      id: '/booking/receipt/$bookingId'
      path: '/booking/receipt/$bookingId'
      fullPath: '/booking/receipt/$bookingId'
      preLoaderRoute: typeof BookingReceiptBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/rate/$bookingId': {
      id: '/booking/rate/$bookingId'
      path: '/booking/rate/$bookingId'
      fullPath: '/booking/rate/$bookingId'
      preLoaderRoute: typeof BookingRateBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/pending/$bookingId': {
      id: '/booking/pending/$bookingId'
      path: '/booking/pending/$bookingId'
      fullPath: '/booking/pending/$bookingId'
      preLoaderRoute: typeof BookingPendingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/message/$bookingId': {
      id: '/booking/message/$bookingId'
      path: '/booking/message/$bookingId'
      fullPath: '/booking/message/$bookingId'
      preLoaderRoute: typeof BookingMessageBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirm/$proId': {
      id: '/booking/confirm/$proId'
      path: '/booking/confirm/$proId'
      fullPath: '/booking/confirm/$proId'
      preLoaderRoute: typeof BookingConfirmProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cancelled/$bookingId': {
      id: '/booking/cancelled/$bookingId'
      path: '/booking/cancelled/$bookingId'
      fullPath: '/booking/cancelled/$bookingId'
      preLoaderRoute: typeof BookingCancelledBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cancel/$bookingId': {
      id: '/booking/cancel/$bookingId'
      path: '/booking/cancel/$bookingId'
      fullPath: '/booking/cancel/$bookingId'
      preLoaderRoute: typeof BookingCancelBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/call/$bookingId': {
      id: '/booking/call/$bookingId'
      path: '/booking/call/$bookingId'
      fullPath: '/booking/call/$bookingId'
      preLoaderRoute: typeof BookingCallBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BizRouteChildren {
  BizSigninRoute: typeof BizSigninRoute
}

const BizRouteChildren: BizRouteChildren = {
  BizSigninRoute: BizSigninRoute,
}

const BizRouteWithChildren = BizRoute._addFileChildren(BizRouteChildren)

interface BookingsRouteChildren {
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface FavoritesRouteChildren {
  FavoritesCollectionIdRoute: typeof FavoritesCollectionIdRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
}

const FavoritesRouteChildren: FavoritesRouteChildren = {
  FavoritesCollectionIdRoute: FavoritesCollectionIdRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
}

const FavoritesRouteWithChildren = FavoritesRoute._addFileChildren(
  FavoritesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileCreditsRoute: typeof ProfileCreditsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileHairProfileRoute: typeof ProfileHairProfileRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileLanguageRoute: typeof ProfileLanguageRoute
  ProfileLegalRoute: typeof ProfileLegalRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePaymentMethodsRoute: typeof ProfilePaymentMethodsRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfilePromotionsRoute: typeof ProfilePromotionsRoute
  ProfileRatingRoute: typeof ProfileRatingRoute
  ProfileReferRoute: typeof ProfileReferRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileTermsRoute: typeof ProfileTermsRoute
  ProfileThemeRoute: typeof ProfileThemeRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileCreditsRoute: ProfileCreditsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileHairProfileRoute: ProfileHairProfileRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileLanguageRoute: ProfileLanguageRoute,
  ProfileLegalRoute: ProfileLegalRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePaymentMethodsRoute: ProfilePaymentMethodsRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfilePromotionsRoute: ProfilePromotionsRoute,
  ProfileRatingRoute: ProfileRatingRoute,
  ProfileReferRoute: ProfileReferRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileTermsRoute: ProfileTermsRoute,
  ProfileThemeRoute: ProfileThemeRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SafetyRouteChildren {
  SafetyDiscreetCallRoute: typeof SafetyDiscreetCallRoute
  SafetyEmergencyContactsRoute: typeof SafetyEmergencyContactsRoute
  SafetyReportRoute: typeof SafetyReportRoute
  SafetyIndexRoute: typeof SafetyIndexRoute
}

const SafetyRouteChildren: SafetyRouteChildren = {
  SafetyDiscreetCallRoute: SafetyDiscreetCallRoute,
  SafetyEmergencyContactsRoute: SafetyEmergencyContactsRoute,
  SafetyReportRoute: SafetyReportRoute,
  SafetyIndexRoute: SafetyIndexRoute,
}

const SafetyRouteWithChildren =
  SafetyRoute._addFileChildren(SafetyRouteChildren)

interface SigninRouteChildren {
  SigninAppleRoute: typeof SigninAppleRoute
  SigninGoogleRoute: typeof SigninGoogleRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninAppleRoute: SigninAppleRoute,
  SigninGoogleRoute: SigninGoogleRoute,
  SigninIndexRoute: SigninIndexRoute,
}

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren)

interface ProProIdRouteChildren {
  ProProIdPortfolioRoute: typeof ProProIdPortfolioRoute
  ProProIdReviewsRoute: typeof ProProIdReviewsRoute
  ProProIdIndexRoute: typeof ProProIdIndexRoute
}

const ProProIdRouteChildren: ProProIdRouteChildren = {
  ProProIdPortfolioRoute: ProProIdPortfolioRoute,
  ProProIdReviewsRoute: ProProIdReviewsRoute,
  ProProIdIndexRoute: ProProIdIndexRoute,
}

const ProProIdRouteWithChildren = ProProIdRoute._addFileChildren(
  ProProIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiometricEnrollRoute: BiometricEnrollRoute,
  BizRoute: BizRouteWithChildren,
  BookingsRoute: BookingsRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRouteWithChildren,
  JoinAsProRoute: JoinAsProRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SafetyRoute: SafetyRouteWithChildren,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRouteWithChildren,
  SignupRoute: SignupRoute,
  SortRoute: SortRoute,
  SplashRoute: SplashRoute,
  UnlockRoute: UnlockRoute,
  WelcomeRoute: WelcomeRoute,
  PoliciesCancellationRoute: PoliciesCancellationRoute,
  ProProIdRoute: ProProIdRouteWithChildren,
  SeeAllCategoryRoute: SeeAllCategoryRoute,
  BookingCallBookingIdRoute: BookingCallBookingIdRoute,
  BookingCancelBookingIdRoute: BookingCancelBookingIdRoute,
  BookingCancelledBookingIdRoute: BookingCancelledBookingIdRoute,
  BookingConfirmProIdRoute: BookingConfirmProIdRoute,
  BookingMessageBookingIdRoute: BookingMessageBookingIdRoute,
  BookingPendingBookingIdRoute: BookingPendingBookingIdRoute,
  BookingRateBookingIdRoute: BookingRateBookingIdRoute,
  BookingReceiptBookingIdRoute: BookingReceiptBookingIdRoute,
  BookingRescheduleBookingIdRoute: BookingRescheduleBookingIdRoute,
  BookingSearchingBookingIdRoute: BookingSearchingBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
