/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BiometricEnrollRouteImport } from './routes/biometric-enroll'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as SeeAllCategoryRouteImport } from './routes/see-all.$category'
import { Route as ProProIdRouteImport } from './routes/pro.$proId'
import { Route as FavoritesCollectionIdRouteImport } from './routes/favorites.$collectionId'
import { Route as FavoritesSharedShareIdRouteImport } from './routes/favorites.shared.$shareId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricEnrollRoute = BiometricEnrollRouteImport.update({
  id: '/biometric-enroll',
  path: '/biometric-enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FavoritesRoute,
} as any)
const SeeAllCategoryRoute = SeeAllCategoryRouteImport.update({
  id: '/see-all/$category',
  path: '/see-all/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProProIdRoute = ProProIdRouteImport.update({
  id: '/pro/$proId',
  path: '/pro/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesCollectionIdRoute = FavoritesCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesSharedShareIdRoute = FavoritesSharedShareIdRouteImport.update({
  id: '/shared/$shareId',
  path: '/shared/$shareId',
  getParentRoute: () => FavoritesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/pro/$proId': typeof ProProIdRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/favorites/shared/$shareId': typeof FavoritesSharedShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/notifications': typeof NotificationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/pro/$proId': typeof ProProIdRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/favorites': typeof FavoritesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/favorites/shared/$shareId': typeof FavoritesSharedShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biometric-enroll': typeof BiometricEnrollRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/unlock': typeof UnlockRoute
  '/welcome': typeof WelcomeRoute
  '/favorites/$collectionId': typeof FavoritesCollectionIdRoute
  '/pro/$proId': typeof ProProIdRoute
  '/see-all/$category': typeof SeeAllCategoryRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/favorites/shared/$shareId': typeof FavoritesSharedShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometric-enroll'
    | '/bookings'
    | '/discover'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/favorites/$collectionId'
    | '/pro/$proId'
    | '/see-all/$category'
    | '/favorites/'
    | '/profile/'
    | '/favorites/shared/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometric-enroll'
    | '/bookings'
    | '/discover'
    | '/notifications'
    | '/signin'
    | '/signup'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/favorites/$collectionId'
    | '/pro/$proId'
    | '/see-all/$category'
    | '/favorites'
    | '/profile'
    | '/favorites/shared/$shareId'
  id:
    | '__root__'
    | '/'
    | '/biometric-enroll'
    | '/bookings'
    | '/discover'
    | '/favorites'
    | '/notifications'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/splash'
    | '/unlock'
    | '/welcome'
    | '/favorites/$collectionId'
    | '/pro/$proId'
    | '/see-all/$category'
    | '/favorites/'
    | '/profile/'
    | '/favorites/shared/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiometricEnrollRoute: typeof BiometricEnrollRoute
  BookingsRoute: typeof BookingsRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  UnlockRoute: typeof UnlockRoute
  WelcomeRoute: typeof WelcomeRoute
  ProProIdRoute: typeof ProProIdRoute
  SeeAllCategoryRoute: typeof SeeAllCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric-enroll': {
      id: '/biometric-enroll'
      path: '/biometric-enroll'
      fullPath: '/biometric-enroll'
      preLoaderRoute: typeof BiometricEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/see-all/$category': {
      id: '/see-all/$category'
      path: '/see-all/$category'
      fullPath: '/see-all/$category'
      preLoaderRoute: typeof SeeAllCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$proId': {
      id: '/pro/$proId'
      path: '/pro/$proId'
      fullPath: '/pro/$proId'
      preLoaderRoute: typeof ProProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/$collectionId': {
      id: '/favorites/$collectionId'
      path: '/$collectionId'
      fullPath: '/favorites/$collectionId'
      preLoaderRoute: typeof FavoritesCollectionIdRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/shared/$shareId': {
      id: '/favorites/shared/$shareId'
      path: '/shared/$shareId'
      fullPath: '/favorites/shared/$shareId'
      preLoaderRoute: typeof FavoritesSharedShareIdRouteImport
      parentRoute: typeof FavoritesRoute
    }
  }
}

interface FavoritesRouteChildren {
  FavoritesCollectionIdRoute: typeof FavoritesCollectionIdRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  FavoritesSharedShareIdRoute: typeof FavoritesSharedShareIdRoute
}

const FavoritesRouteChildren: FavoritesRouteChildren = {
  FavoritesCollectionIdRoute: FavoritesCollectionIdRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  FavoritesSharedShareIdRoute: FavoritesSharedShareIdRoute,
}

const FavoritesRouteWithChildren = FavoritesRoute._addFileChildren(
  FavoritesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiometricEnrollRoute: BiometricEnrollRoute,
  BookingsRoute: BookingsRoute,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  UnlockRoute: UnlockRoute,
  WelcomeRoute: WelcomeRoute,
  ProProIdRoute: ProProIdRoute,
  SeeAllCategoryRoute: SeeAllCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
